package pk.addressbook;// Generated by Selenium IDE
import org.junit.Test;

public class CreateNewContactTest extends TestBase{
  
  @Test
  public void createNewContact() {

    goToNewContactCreationPage();
    fillTheContactForm(new ContactData("Nick", "Yellow", "7-777-777", "thesecond@mail.com"));
    submitNewContactCreation();
  }

}
