package pk.addressbook;// Generated by Selenium IDE
import org.junit.Test;
public class GroupCreationTests extends TestBase {

  @Test
  public void testGroupCreation() {
    goToGroupPage();
    initGroupCreation();
    fillGroupForm(new GroupData("new group", "new header", "new footer"));
    submitGroupCreation();
    goToGroupPage();
  }

}
