package pk.addressbook.tests;// Generated by Selenium IDE

import org.testng.Assert;
import org.testng.annotations.Test;
import pk.addressbook.model.ContactData;

import java.util.Set;

public class CreateNewContactTest extends TestBase {
    @Test
    public void createNewContact() {
        app.goTo().homePage();
        Set<ContactData> before = app.contact().all();
        ContactData contact = new ContactData().withName("Nick").withLastName("Yellow").withAddress("LA")
                .withMail("thesecond@mail.com").withGroup(app.contact().getGroupName());
        app.contact().createContact(contact, true);
        Set<ContactData> after = app.contact().all();
        Assert.assertEquals(after.size(), before.size() + 1);

        contact.withId(after.stream().mapToInt((c) -> c.id()).max().getAsInt());
        before.add(contact);
        Assert.assertEquals(before, after);

    }

}
