package pk.addressbook.tests;// Generated by Selenium IDE
import org.junit.Test;
import pk.addressbook.model.GroupData;

public class GroupCreationTests extends TestBase {

  @Test
  public void testGroupCreation() {
    app.getNavigationHelper().goToGroupPage();
    app.getGroupHelper().createGroup(new GroupData("new group", "new header", "new footer"));

  }

}
